### PR TITLE
localStorage and changes to editor UI 

### PR DESCRIPTION
**Pull request by nategreb**
LocalStorage:  Located in GameEditor/Controllers. Purpose is to save the state of the edited game across different pages. We want one object all throughout

### CODE REVIEW

**Review by tomking — DISMISSED** [review]
Looks fine to me. @imnnos @kunjdedhia any comments ?

**Review by ygbull — DISMISSED** [review]
Looks good to me @nategreb

**Review by ygbull — COMMENTED** [review]
Not sure if it's a big issue, but seems like the `Rule Editor -> Movement Rule -> Radio Button` text color is unmatched with the background. It would be easily fixed by a few lines of CSS or setStyle

**Review by ygbull — APPROVED** [review]

**Comment by imnnos** [comment]
@tomking Only changes to Objects were in slimming down the imports which is fine with me.

**Pull request merged**
