### PR TITLE
Cleanup and combine Team Team and te4m code

### PR DESCRIPTION
**Pull request by tomking**
The stateobject-cleanup branch contains the semi-finalized combination of Team Team and Te4m's code. Persisted object classes are found in src/Objects and runtime-only object classes can be found in src/State.

### CODE REVIEW

**Review by kunjdedhia — APPROVED** [review]

**Review by ygbull — CHANGES_REQUESTED** [review]
The [Demo.java](https://github.com/david-fisher/320-F21-Track-1/blob/stateobject-cleanup/src/State/Demo.java) needs to be put in a package and possibly import Object*

**Review by kunjdedhia — DISMISSED** [review]

**Comment by tomking** [comment]
Alright, @ygbull we removed te4m's demo file. It shouldn't be needed anymore. Does Team Team still need that old demo file @SiegAndy @sasana-uwu ?

**Review by ygbull — COMMENTED** [review]
@tomking Aight I see the new update. I am not sure if it's an issue supposed to fix by you guys but seems like the project is not able to compile due to a type mismatch in [RNGController.java](https://github.com/david-fisher/320-F21-Track-1/blob/stateobject-cleanup/src/GameEditor/Controllers/RNGController.java). Is the code compilable on your machine? @tomking

**Comment by tomking** [comment]
@ygbull Yeah that isn't our team's file, it is possible that we broke something there but I do not know. @kunjdedhia @imnnos any ideas about this? I'll try to check it out tomorrow.

**Comment by ygbull** [comment]
> @ygbull Yeah that isn't our team's file, it is possible that we broke something there but I do not know. @kunjdedhia @imnnos any ideas about this? I'll try to check it out tomorrow.

Yeah, it happens. It should be solvable by either making the int into double or the other around. Just make sure it's compilable.

**Comment by tomking** [comment]
Ah gotcha, I'm on my phone so I didn't look at the file. We will get it fixed and committed here.

**Comment by ygbull** [comment]
Sounds good @tomking

**Comment by tomking** [comment]
Alright @ygbull I think that is what we are going with for now. Hopefully that doesn't break anything else, we will have to be in touch with Fisher's Fish about it... @nategreb @Sad-0w see latest commit to this PR. We don't want people to be able to set floating point numbers as the min/max of a range for an RNG, only ints. Thank you all for continuing to work with us on all of this.

**Review by ygbull — DISMISSED** [review]
It looks good to me @tomking

**Review by kunjdedhia — APPROVED** [review]

**Review by imnnos — APPROVED** [review]

**Comment by tomking** [comment]
Any feedback from Team Team @sasana-uwu @SiegAndy ?

Or anything of note from Fisher's Fish @nategreb @Sad-0w ?

And any progress on the stuff you were talking about doing on Slack @userazhao ? I don't think there is any reason that work couldn't just be done after this is merged in as long as you don't have any objections to this PR.

**Comment by imnnos** [comment]
> Any feedback from Team Team @sasana-uwu @SiegAndy ?
> 
> Or anything of note from Fisher's Fish @nategreb @Sad-0w ?
> 
> And any progress on the stuff you were talking about doing on Slack @userazhao ? I don't think there is any reason that work couldn't just be done after this is merged in as long as you don't have any objections to this PR.

+1. We need to go ahead and get this PR merged so that integration can move forward after the meeting tomorrow.

**Comment by nategreb** [comment]
@Sad-0w See above comment: "We don't want people to be able to set floating point numbers as the min/max of a range for an RNG, only ints." They modified it to ints.

**Comment by tomking** [comment]
@nategreb Does that change cause major issues for you guys?

**Comment by nategreb** [comment]
> @nategreb Does that change cause major issues for you guys?

No, it doesn't. 
Go ahead and merge.

**Comment by tomking** [comment]
> > @nategreb Does that change cause major issues for you guys?
> 
> No, it doesn't. Go ahead and merge.

Okay awesome, thank you for the feedback. Would you mind giving the PR an approval in that case?

(Just a note as well, we are still waiting for Team Team to give us any input)

**Review by nategreb — APPROVED** [review]

**Review by kunjdedhia — APPROVED** [review]

**Review by Sad-0w — APPROVED** [review]

**Review by SiegAndy — COMMENTED** [review]
reviewed

**Review by SiegAndy — APPROVED** [review]

**Pull request merged**
